# Generated by Django 2.1.7 on 2019-04-02 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('N', 'New'), ('P', 'Processed'), ('C', 'Cancel')], default='N', max_length=2),
        ),
    ]
