# Generated by Django 2.1.7 on 2019-04-02 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190402_1137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='timing',
        ),
        migrations.AddField(
            model_name='profile',
            name='session_1_end_date',
            field=models.CharField(blank=True, choices=[('8:30 AM', '8:30 AM'), ('9:30 AM', '9:30 AM'), ('10:30 AM', '10:30 AM'), ('11:30 AM', '11:30 AM'), ('12:30 AM', '12:30 AM'), ('1:30 AM', '1:30 AM'), ('2:30 AM', '2:30 AM'), ('3:30 AM', '3:30 AM'), ('4:30 AM', '4:30 AM'), ('5:30 AM', '5:30 AM')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='session_1_start_date',
            field=models.CharField(blank=True, choices=[('8:30 AM', '8:30 AM'), ('9:30 AM', '9:30 AM'), ('10:30 AM', '10:30 AM'), ('11:30 AM', '11:30 AM'), ('12:30 AM', '12:30 AM'), ('1:30 AM', '1:30 AM'), ('2:30 AM', '2:30 AM'), ('3:30 AM', '3:30 AM'), ('4:30 AM', '4:30 AM'), ('5:30 AM', '5:30 AM')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='session_2_end_date',
            field=models.CharField(blank=True, choices=[('8:30 AM', '8:30 AM'), ('9:30 AM', '9:30 AM'), ('10:30 AM', '10:30 AM'), ('11:30 AM', '11:30 AM'), ('12:30 AM', '12:30 AM'), ('1:30 AM', '1:30 AM'), ('2:30 AM', '2:30 AM'), ('3:30 AM', '3:30 AM'), ('4:30 AM', '4:30 AM'), ('5:30 AM', '5:30 AM')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='session_2_start_date',
            field=models.CharField(blank=True, choices=[('8:30 AM', '8:30 AM'), ('9:30 AM', '9:30 AM'), ('10:30 AM', '10:30 AM'), ('11:30 AM', '11:30 AM'), ('12:30 AM', '12:30 AM'), ('1:30 AM', '1:30 AM'), ('2:30 AM', '2:30 AM'), ('3:30 AM', '3:30 AM'), ('4:30 AM', '4:30 AM'), ('5:30 AM', '5:30 AM')], max_length=10, null=True),
        ),
    ]
