# Generated by Django 2.1.7 on 2019-04-02 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190402_1325'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='session_1_end_date',
            new_name='session_1_end',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='session_1_start_date',
            new_name='session_1_start',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='session_2_end_date',
            new_name='session_2_end',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='session_2_start_date',
            new_name='session_2_start',
        ),
    ]
