# Generated by Django 2.1.7 on 2019-03-12 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_auto_20190312_1047'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hospital',
            options={'ordering': ['-created_date']},
        ),
    ]
