# Generated by Django 2.1.7 on 2019-03-12 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_auto_20190312_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='detail',
            field=models.TextField(blank=True, null=True),
        ),
    ]
