# Generated by Django 2.1.7 on 2019-03-18 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0005_auto_20190312_1249'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hospital',
            options={'ordering': ['id']},
        ),
    ]
